# -*- coding: utf-8 -*-
"""Spotify Data Analysis project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QEQgsLo3G6PnpGs3KmQgnTt0sH6KVf_R
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df_track = pd.read_csv('tracks.csv')

df_track.head()

pd.isnull(df_track).sum()

sorted_df=df_track.sort_values('popularity').head(10)
sorted_df

df_track.describe().transpose()

mostpopular=df_track.query('popularity>90',inplace=False).sort_values('popularity',ascending=False).head(10)

df_track["duration"]=df_track["duration_ms"].apply(lambda x:round(x/1000))
df_track.drop("duration_ms",inplace=True,axis=1)

df_track.duration.head()

corr = df_track.drop(["key", "mode", "explicit"], axis=1).select_dtypes(include=[np.number]).corr(method="pearson")

plt.figure(figsize=(12,6))
heatmap=sns.heatmap(corr,annot=True,fmt=".1g",vmin=-1,vmax=1,center=0,cmap="inferno",linewidths=1,linecolor= "Black")
heatmap.set_title("correlation")
heatmap.set_xticklabels(heatmap.get_xticklabels(),rotation=90)

sample_df=df_track.sample(int(0.004*len(df_track)))
print(len(sample_df))

plt.figure(figsize=(8,5))
sns.regplot(data=sample_df,y="loudness",x="energy",color="c").set(title="lodness vs energy")

plt.figure(figsize=(8,5))
sns.regplot(data=sample_df,y="popularity",x="acousticness",color="c").set(title="popularity vs acousticness")

print("Index name:", df_track.index.name)

df_track = df_track.reset_index(drop=True)

# Set 'release_date' as the index
df_track.set_index('release_date', inplace=True)

df_track['dates'] = df_track.index.get_level_values('release_date')
df_track.dates = pd.to_datetime(df_track.dates)
years = df_track.dates.dt.year

sns.displot(years,discrete=True,aspect=2,height=5,kind="hist").set(title="no of songs per yr")

df_track.head()

total_dr=df_track.duration

fig_dims=(18,7)
fig,ax=plt.subplots(figsize=fig_dims)
fig=sns.barplot(x=years,y=total_dr,ax=ax,errwidth=False).set(title="year vs duration")
plt.xticks(rotation=90)

total_dr=df_track.duration
sns.set_style(style="whitegrid")
fig_dims=(18,7)
fig,ax=plt.subplots(figsize=fig_dims)
fig=sns.barplot(x=years,y=total_dr,ax=ax).set(title="year vs Duration")
plt.xticks(rotation=90)

total_dr=df_track.duration
sns.set_style(style="whitegrid")
fig_dims=(18,7)
fig,ax=plt.subplots(figsize=fig_dims)
fig=sns.lineplot(x=years,y=total_dr,ax=ax).set(title="year vs Duration")
plt.xticks(rotation=90)

df_genre=pd.read_csv("SpotifyFeatures.csv")

df_genre

df_genre.head()



plt.title("Duration of the songs in different genres")
sns.color_palette("rocket",as_cmap=True)
sns.barplot(y="genre",x="duration_ms",data=df_genre)
plt.xlabel("Duration in milli seconds")
plt.ylabel("Genres")

sns.set_style(style="darkgrid")
plt.figure(figsize=(10,5))
famous=df_genre.sort_values("popularity",ascending=False).head(5)
sns.barplot(y="genre",x="popularity",data=famous).set(title="Top 5 Genres by Popularity")

